(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> <Values at 0x8c1dbcc: {'verbose': False, 'ip': '0.0.0.0', 'debuglevel': 30, 'with_scheduler': False, 'ips': ['127.0.1.1'], 'shutdown_timeout': 5, 'taskbar': False, 'with_coverage': False, 'scheduler_groups': None, 'port': 8000, 'maxthreads': None, 'softcron': False, 'server_name': 'vm-01', 'bpython': False, 'nogui': True, 'pid_filename': 'httpserver.pid', 'print_errors': False, 'extcron': False, 'runcron': False, 'run_system_tests': False, 'test': None, 'folder': '/home/ubuntu/web2py', 'config': '', 'minthreads': None, 'shell': None, 'run': '', 'log_filename': 'httpserver.log', 'profiler_dir': None, 'args': [''], 'socket_timeout': 5, 'ssl_ca_certificate': None, 'scheduler': None, 'interfaces': None, 'ssl_private_key': '', 'gae': None, 'password': '111', 'request_queue_size': 5, 'ssl_certificate': '', 'cronjob': False, 'numthreads': None, 'quiet': False, 'import_models': False, 'timeout': 10, 'plain': False, 'nobanner': False}> is not JSON serializable"
p3
sS'layer'
p4
S'/home/ubuntu/web2py/applications/api/views/generic.json'
p5
sS'code'
p6
S"from gluon.serializers import json\nresponse.write(XML(json(response._vars)))\nresponse.write('\\n', escape=False)"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ubuntu/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/ubuntu/web2py/applications/api/views/generic.json", line 2, in <module>\n  File "/home/ubuntu/web2py/gluon/serializers.py", line 135, in json\n    value = json_parser.dumps(value, default=default, use_decimal=False)\n  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 296, in dumps\n    **kw).encode(obj)\n  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 226, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 296, in iterencode\n    return _iterencode(o, 0)\n  File "/home/ubuntu/web2py/gluon/serializers.py", line 110, in custom_json\n    raise TypeError(repr(o) + " is not JSON serializable")\nTypeError: <Values at 0x8c1dbcc: {\'verbose\': False, \'ip\': \'0.0.0.0\', \'debuglevel\': 30, \'with_scheduler\': False, \'ips\': [\'127.0.1.1\'], \'shutdown_timeout\': 5, \'taskbar\': False, \'with_coverage\': False, \'scheduler_groups\': None, \'port\': 8000, \'maxthreads\': None, \'softcron\': False, \'server_name\': \'vm-01\', \'bpython\': False, \'nogui\': True, \'pid_filename\': \'httpserver.pid\', \'print_errors\': False, \'extcron\': False, \'runcron\': False, \'run_system_tests\': False, \'test\': None, \'folder\': \'/home/ubuntu/web2py\', \'config\': \'\', \'minthreads\': None, \'shell\': None, \'run\': \'\', \'log_filename\': \'httpserver.log\', \'profiler_dir\': None, \'args\': [\'\'], \'socket_timeout\': 5, \'ssl_ca_certificate\': None, \'scheduler\': None, \'interfaces\': None, \'ssl_private_key\': \'\', \'gae\': None, \'password\': \'111\', \'request_queue_size\': 5, \'ssl_certificate\': \'\', \'cronjob\': False, \'numthreads\': None, \'quiet\': False, \'import_models\': False, \'timeout\': 10, \'plain\': False, \'nobanner\': False}> is not JSON serializable\n'
p11
s.